version: "3.8"

services:
  app:
    build:
      context: ./project
    entrypoint: ['/app/entrypoint.sh']
    volumes:
      - .:/app
    ports:
      - 5001:5000
    env_file:
      - .env

  db:
    build:
      context: ./project/db

    expose:
      - 5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    build:
      context: ./frontend

    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - app


