version: "3.7"

services:
  backend:
    build:
      context: ./project
      dockerfile: Dockerfile.backend

    volumes:
      - "./project/backend:/app"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./project/frontend

    volumes:
      - "./project/frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - backend
