version: "3.8"

services:
  app:
    build:
      context: ./project/api
    entrypoint: ['/app/entrypoint.sh']
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend

    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - app


  db:
    build:
      context: ./project/db

    expose:
      - 5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres




