version: "3.7"

services:
  backend:
    build:
      context: ./project

    volumes:
      - "./project/backend:/app"
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: ./project/frontend

    volumes:
      - "./project/frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    build:
      context: ./project/db

    volumes:
      - "./project/frontend:/app"

    expose:
      - 5432

    env_file:
      - ./.env
    depends_on:
      - backend



